name: github-actions-example
on: [push]
jobs:
  run-boozang-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm install
      - run: npm run server & npm start & npx wait-on http://localhost:3000
      - run: curl http://localhost:3000

      - name: Run headless test with Boozang
        run: |
          docker run --network host -v ${{ github.workspace }}/json:/var/boozang/json styrman/boozang-runner "https://staging-bh.boozang.com/extension?token=476599f569bae30b24bfd3a7b6c450d2697a833bfce5889460cea7f8&env=0&key=1#697a833bfce5889460cea7f8/master/m1/t2/run"

      - run: npm install multiple-cucumber-html-reporter --save-dev && node reporter.js
        if: always()

      - name: Deploy report page
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
